name: Build packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.5
        arch:
          - aarch64_cortex-a53

    steps:
      - uses: actions/checkout@v4

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: ./
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          NO_DEFAULT_FEEDS: 1
          EXTRA_FEEDS: src-git|packages|https://git.openwrt.org/project/omcproxy.git^9ddc2c5dcdf3f9470ad8ad1ce7d412460b6c5f91
          PACKAGES: omcproxy

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.release }}-packages
          path: |
            bin/packages/${{ matrix.arch }}/packages/*.[ai]pk
            ${{ github.workspace }}/artifacts/bin/**/*.[ai]pk
          if-no-files-found: ignore
          overwrite: true
