name: Build packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.5
        arch:
          - aarch64_cortex-a53

    steps:
      - uses: actions/checkout@v4

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: ./
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: omcproxy

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.release }}-packages
          path: |
            bin/packages/${{ matrix.arch }}/packages/*.[ai]pk
            bin/packages/${{ matrix.arch }}-${{ matrix.release }}/packages/*.[ai]pk
            bin/packages/${{ matrix.arch }}/*.[ai]pk
            bin/packages/${{ matrix.arch }}-${{ matrix.release }}/*.[ai]pk
            bin/${{ matrix.arch }}/packages/*.[ai]pk
            bin/${{ matrix.arch }}-${{ matrix.release }}/packages/*.[ai]pk
            bin/${{ matrix.arch }}/*.[ai]pk
            bin/${{ matrix.arch }}-${{ matrix.release }}/*.[ai]pk
            ${{ github.workspace }}/artifacts/*.[ai]pk
            ${{ github.workspace }}/artifacts/bin/*.[ai]pk
            ${{ github.workspace }}/artifacts/bin/${{ matrix.arch }}/*.[ai]pk
            ${{ github.workspace }}/artifacts/bin/${{ matrix.arch }}-${{ matrix.release }}/*.[ai]pk
            ${{ github.workspace }}/artifacts/**/*.[ai]pk
          if-no-files-found: ignore
          overwrite: true
